# Generated by Django 5.1 on 2024-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Bahawalpur', 'Bahawalpur'), ('Multan', 'Multan'), ('Hyderabad', 'Hyderabad')], max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('temp', models.FloatField()),
                ('temp_feels_like', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('wind_dir', models.CharField(max_length=100)),
                ('timezone', models.IntegerField()),
            ],
        ),
    ]
