# Generated by Django 5.1 on 2024-08-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='day_1_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_2_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_3_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_4_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_5_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_6_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_7_temp',
            field=models.FloatField(default=0),
        ),
    ]
