# Generated by Django 5.1 on 2024-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weather_day_1_temp_weather_day_2_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='day_1_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_2_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_3_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_4_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_5_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_6_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weather',
            name='day_7_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
