# Generated by Django 5.1 on 2024-08-21 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weather_day_1_name_weather_day_2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
