# Generated by Django 5.1 on 2024-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_weather_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
