# Generated by Django 5.1 on 2024-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_crop_province_alter_weather_day_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='day_0_temp',
            field=models.FloatField(default=0),
        ),
    ]
