# Generated by Django 5.1 on 2024-08-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_weather_day_0_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='region',
            name='radius',
            field=models.IntegerField(default=0),
        ),
    ]
